---
- name: Include label hosts
  include_tasks: label-hosts.yaml

- name: Include Tasks Calico
  include_tasks: calico.yaml
  when: ilke_network.cni_plugin == 'calico'

- name: Include Tasks Kube-router
  include_tasks: kube-router.yaml
  when: ilke_network.cni_plugin == 'kube-router'

- name: Deploy CoreDNS to K8S
  include_tasks: coredns.yaml

- name: Install MetalLB Layer2
  include_tasks: metallb_l2.yaml
  when: ilke_network.external_loadbalancing.enabled | bool == True

- name: Install Metrics-Server
  include_tasks: metrics-server.yaml
  when: ilke_features.metrics_server.enabled | bool == True

- name: Install Reloader
  include_tasks: reloader.yaml
  when: ilke_features.reloader.enabled | bool == True

- name: Install logrotate
  include_tasks: logrotate.yaml
  when: ilke_features.logrotate.enabled | bool == True

- name: Install ingress (traefik)
  include_tasks: traefik.yaml
  when: ilke_features.ingress.controller == 'traefik'

- name: Install ingress (haproxy)
  include_tasks: haproxy.yaml
  when: ilke_features.ingress.controller == 'haproxy'

- name: Install ingress (nginx)
  include_tasks: nginx.yaml
  when: ilke_features.ingress.controller == 'nginx'

- name: Install K8S Default Dashboard
  include_tasks: default_dashboard.yaml
  when: ilke_features.dashboard.enabled | bool == True

- name: Install openebs for persistence
  include_tasks: openebs.yaml
  when: ilke_features.storage.enabled | bool == True

- name: Install Monitoring
  include_tasks: monitoring.yaml
  when: ilke_features.monitoring.enabled | bool == True

- name: enable etcd backup cronJob
  include_tasks: backup-etcd-cronjob.yaml
  when: ilke_base_components.etcd.backup.enabled | bool == True

- name: Install Gatekeeper
  include_tasks: gatekeeper.yaml
  when: ilke_features.gatekeeper.enabled | bool == True
